name:                ovn-tool
version:             0.1.0.0
github:              "githubuser/ovn-tool"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ovn-tool#readme>

flags:
  static:
    description: Emit statically-linked binary
    manual: False
    default: False

  optimized:
    description: Perform compiler optimizations
    manual: False
    default: False

dependencies:
- base >= 4.7 && < 5
- protolude  >= 0.2
- cryptonite
- bytestring
- random
- memory
- optparse-applicative

library:
  source-dirs: src
  exposed-modules:
    - Curve
    - CurveAltBn128G1
    - Lib

executables:
  ovn-tool-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ovn-tool

tests:
  ovn-tool-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ovn-tool
